# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.0.1-alpha'
git_version = '89e10c1650be66df51ed5b0ad6015262a923ec5e'
